const roles={andrea:{name:"Andrea",full:"Andrea Castellazzo",initials:"AC",role:"Operativo · commerciale",summary:"Hai 5 cose che richiedono attenzione. Partiamo da quelle importanti.",tone:"lilac",finance:true,insights:false},simone:{name:"Simone",full:"Simone Maffessoni",initials:"SM",role:"Direzione · amministratore",summary:"Hai 7 decisioni e 3 anomalie da risolvere. Il lavoro operativo resta in secondo piano.",tone:"dark",finance:true,insights:true},martina:{name:"Martina",full:"Martina Riva",initials:"MR",role:"Operativa · graphic designer",summary:"Hai 4 attività, una consegna e una nuova revisione da gestire.",tone:"mint",finance:false,insights:false},luca:{name:"Luca",full:"Luca Moretti",initials:"LM",role:"Operativo · videomaker",summary:"Il tuo carico è oltre la capacità: prima risolviamo il conflitto, poi il resto.",tone:"peach",finance:false,insights:false}};
const labels={today:"Oggi",opportunities:"Opportunità",projects:"Progetti",calendar:"Calendario",clients:"Clienti",team:"Team",finance:"Amministrazione",insights:"Insight"};
let currentRole="andrea";
const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];

function showView(view){if(!$("#view-"+view))return;$$('[data-view-panel]').forEach(p=>p.classList.toggle("is-active",p.dataset.viewPanel===view));$$('[data-view]').forEach(b=>b.classList.toggle("is-active",b.dataset.view===view));$("#currentViewLabel").textContent=labels[view];history.replaceState(null,"","#"+view);window.scrollTo({top:0,behavior:"smooth"})}
function toast(message){$("#toastText").textContent=message;$("#toast").classList.add("is-visible");clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$("#toast").classList.remove("is-visible"),2400)}
function applyRole(key,notify=true){const role=roles[key];currentRole=key;$$('[data-person-name]').forEach(e=>e.textContent=role.name);$$('[data-person-role]').forEach(e=>e.textContent=role.role);$$('[data-avatar]').forEach(e=>{const small=e.classList.contains("small")?" small":"";e.textContent=role.initials;e.className="avatar"+small+" "+role.tone});$("#roleSummary").textContent=role.summary;$$('[data-permission="finance"]').forEach(e=>e.classList.toggle("role-restricted",!role.finance));$$('[data-permission="insights"]').forEach(e=>e.classList.toggle("role-restricted",!role.insights));$$('#rolePopover [data-role]').forEach(b=>b.querySelector("b").textContent=b.dataset.role===key?"✓":"");$("#rolePopover").hidden=true;if((!role.finance&&location.hash==="#finance")||(!role.insights&&location.hash==="#insights"))showView("today");if(notify)toast(`Vista aggiornata per ${role.full}`)}
function updateClock(){const now=new Date(),h=now.getHours();$("#greeting").textContent=h>=4&&h<18?"Buongiorno":"Buonasera";$("#liveTime").textContent=now.toLocaleTimeString("it-IT",{hour:"2-digit",minute:"2-digit"});$("#todayDate").textContent=now.toLocaleDateString("it-IT",{weekday:"long",day:"numeric",month:"long"})}

$$('[data-view]').forEach(b=>b.addEventListener("click",()=>showView(b.dataset.view)));$$('[data-view-jump]').forEach(b=>b.addEventListener("click",()=>showView(b.dataset.viewJump)));
const rolePopover=$("#rolePopover");function toggleRoles(e){e.stopPropagation();rolePopover.hidden=!rolePopover.hidden;$("#notifications").hidden=true}$("#roleSwitch").addEventListener("click",toggleRoles);$("#profileButton").addEventListener("click",toggleRoles);$$('[data-role]').forEach(b=>b.addEventListener("click",()=>applyRole(b.dataset.role)));
$("#notificationButton").addEventListener("click",e=>{e.stopPropagation();const p=$("#notifications");p.hidden=!p.hidden;rolePopover.hidden=true});$("#closeNotifications").addEventListener("click",()=>$("#notifications").hidden=true);document.addEventListener("click",e=>{if(!e.target.closest(".popover")&&!e.target.closest("#roleSwitch")&&!e.target.closest("#profileButton")&&!e.target.closest("#notificationButton")){rolePopover.hidden=true;$("#notifications").hidden=true}});
const modal=$("#opportunityModal");function closeModal(){modal.hidden=true;document.body.style.overflow=""}$$('[data-open-modal]').forEach(b=>b.addEventListener("click",()=>{modal.hidden=false;document.body.style.overflow="hidden";setTimeout(()=>modal.querySelector("input").focus(),50)}));$$('[data-close-modal]').forEach(b=>b.addEventListener("click",closeModal));modal.addEventListener("click",e=>{if(e.target===modal)closeModal()});$("#advancedToggle").addEventListener("click",()=>{const f=$("#advancedFields");f.hidden=!f.hidden;$("#advancedToggle").textContent=f.hidden?"＋ Aggiungi stima o servizi":"− Nascondi dettagli aggiuntivi"});$("#opportunityForm").addEventListener("submit",e=>{e.preventDefault();const client=new FormData(e.currentTarget).get("client");closeModal();e.currentTarget.reset();toast(`${client} aggiunto alle opportunità`)});
$$('[data-toast]').forEach(b=>b.addEventListener("click",()=>toast(b.dataset.toast)));$$('.task-row input').forEach(i=>i.addEventListener("change",()=>{if(i.checked)toast("Attività completata")}));$$('[data-task-filter]').forEach(b=>b.addEventListener("click",()=>{const state=b.dataset.taskFilter;$$('[data-task-filter]').forEach(x=>x.classList.toggle("is-active",x===b));$$('[data-task-state]').forEach(r=>r.style.display=r.dataset.taskState===state?"grid":"none")}));
$$('[data-pipeline-filter]').forEach(b=>b.addEventListener("click",()=>{const filter=b.dataset.pipelineFilter;$$('[data-pipeline-filter]').forEach(x=>x.classList.toggle("is-active",x===b));$$('.opportunity-card').forEach(c=>c.style.display=filter==="all"||filter==="mine"&&c.dataset.owner===roles[currentRole].name||filter==="late"&&c.dataset.late==="true"?"block":"none")}));$("#opportunitySearch").addEventListener("input",e=>{const q=e.target.value.toLowerCase();$$('.opportunity-card').forEach(c=>c.style.display=c.textContent.toLowerCase().includes(q)?"block":"none")});
$$('.project-row').forEach(r=>r.addEventListener("click",()=>{$("#projectDrawer").classList.add("is-open");$("#projectDrawer").setAttribute("aria-hidden","false")}));$("#closeDrawer").addEventListener("click",()=>{$("#projectDrawer").classList.remove("is-open");$("#projectDrawer").setAttribute("aria-hidden","true")});document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeModal();$("#projectDrawer").classList.remove("is-open");rolePopover.hidden=true;$("#notifications").hidden=true}});$("#searchButton").addEventListener("click",()=>toast("Ricerca globale prevista nella prossima iterazione"));
updateClock();setInterval(updateClock,60000);applyRole("andrea",false);const initial=location.hash.slice(1);if(labels[initial])showView(initial);
